hotel-management-mvc/Models/Room.cs
using System;
using System.Collections.Generic;

namespace hotel_management_mvc.Models;

public partial class Room
{
    public int Id { get; set; }

    public string Code { get; set; } = null!;

    public decimal Price { get; set; }

    public string? Services { get; set; }

    public RoomStatus RoomStatus { get; set; }

    public virtual ICollection<RoomBooking> RoomBookings { get; set; } = new List<RoomBooking>();

    public virtual ICollection<RoomTransaction> RoomTransactions { get; set; } = new List<RoomTransaction>();
}

hotel-management-mvc/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hotel_management_mvc.Models;
using Newtonsoft.Json;

namespace hotel_management_mvc.Controllers
{
    public class RoomsController : Controller
    {
        private readonly HotelManagementContext _context;

        public RoomsController(HotelManagementContext context)
        {
            _context = context;
            UpdateRoomStatus();
        }

        // GET: Rooms
        public async Task<IActionResult> Index(string searchString)
        {
            var room = await _context.Rooms.ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                room = room.Where(x => x.Code.Trim().ToLower().Contains(searchString.Trim().ToLower()) || x.Services.Trim().ToLower().Contains(searchString.Trim().ToLower())).ToList();
            }
            return room != null ?
                          View(room) :
                          Problem("Entity set 'HotelManagementContext.Rooms'  is null.");
        }

        // GET: Rooms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // GET: Rooms/Create
        public IActionResult Create()
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            return View();
        }

        // POST: Rooms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,Price,Services")] Room room)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (ModelState.IsValid)
            {
                room.RoomStatus = RoomStatus.Empty;
                _context.Add(room);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: Rooms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,Price,Services,RoomStatus")] Room room)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id != room.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(room);
        }

        // GET: Rooms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (id == null || _context.Rooms == null)
            {
                return NotFound();
            }

            var room = await _context.Rooms
                .FirstOrDefaultAsync(m => m.Id == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: Rooms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (_context.Rooms == null)
            {
                return Problem("Entity set 'HotelManagementContext.Rooms'  is null.");
            }
            var room = await _context.Rooms.FindAsync(id);
            if (room != null)
            {
                _context.Rooms.Remove(room);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(int id)
        {
            return (_context.Rooms?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        private void UpdateRoomStatus()
        {
            var rooms = _context.Rooms.Include(x => x.RoomBookings).ThenInclude(x => x.Booking).Where(x => x.RoomStatus == RoomStatus.Booked).ToList();
            foreach (var room in rooms)
            {
                foreach (var item in room.RoomBookings)
                {
                    if (item.Booking.Checkout <= DateTime.Now)
                    {
                        room.RoomStatus = RoomStatus.Empty;
                    }
                }
            }
            _context.UpdateRange(rooms);
            _context.SaveChanges();
        }
    }
}

hotel-management-mvc/Views/Rooms/Create.cshtml
@model hotel_management_mvc.Models.Room

@{
    ViewData["Title"] = "Create";
}

<div class="edit-header">
    <h4>Create Room</h4>
    <div>
        <a asp-action="Index" class="btn btn-primary m-1">Back to Room List</a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Services" class="control-label"></label>
                <input asp-for="Services" class="form-control" />
                <span asp-validation-for="Services" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hotel-management-mvc/Views/Rooms/Delete.cshtml
@model hotel_management_mvc.Models.Room

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Services)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Services)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomStatus)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

hotel-management-mvc/Views/Rooms/Details.cshtml
@model hotel_management_mvc.Models.Room

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Room</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Code)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Code)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Services)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Services)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomStatus)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

hotel-management-mvc/Views/Rooms/Edit.cshtml
@model hotel_management_mvc.Models.Room

@{
    ViewData["Title"] = "Edit";
}

<div class="edit-header">
    <h4>Edit</h4>
    <div>
        <a asp-action="Index" class="btn btn-primary m-1">Back to Room List</a>
    </div>
</div>
<hr />

<div class="edit-container">
    <div class="edit-container-image">
        <img src="https://cdn5.vectorstock.com/i/1000x1000/93/24/hotel-room-key-with-number-icon-graph-symbol-vector-47849324.jpg" alt="...">
    </div>
    <div class="edit-container-body">
        <form asp-action="Edit" class="edit-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Services" class="control-label"></label>
                <input asp-for="Services" class="form-control" />
                <span asp-validation-for="Services" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomStatus" class="control-label"></label>
                <select asp-for="RoomStatus" class="form-control">
                    <option value="1">Empty</option>
                    <option value="2">Booked</option>
                    <option value="3">UnderConstruction</option>
                </select>
                <span asp-validation-for="RoomStatus" class="text-danger"></span>
            </div>
            <div class="form-group mt-3 save-button">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hotel-management-mvc/Views/Rooms/Index.cshtml
@model IEnumerable<hotel_management_mvc.Models.Room>

@{
    ViewData["Title"] = "Room - Hotel Management";
}

<div class="page-header">
    <h1><strong>Room List</strong></h1>
</div>
<div class="page-title">
    <div class="page-title-search">
        <form asp-controller="Rooms" asp-action="Index">
            <p>
                Search: <input type="text" name="SearchString" />
                <input type="submit" value="Search" />
            </p>
        </form>
    </div>
    <p class="page-title-button">
        <a asp-action="Create" class="btn btn-primary m-1" style="width: 100%;">Add new Room</a>
    </p>
</div>
<div class="list-container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-3">
                <div class="card p-2 m-2" style="min-width: 20rem;">
                    <img src="https://cdn5.vectorstock.com/i/1000x1000/93/24/hotel-room-key-with-number-icon-graph-symbol-vector-47849324.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Room No: @item.Code</h5>
                        <p class="card-text mt-2">Price: @item.Price</p>
                        <p class="card-text">Services: @item.Services</p>
                        <div class="card-text d-flex justify-content-start">
                            <div class="me-3">
                                Room Status:
                            </div>
                            <div>
                                @{
                                    if (@item.RoomStatus == RoomStatus.Empty)
                                    {
                                        <span class="badge text-bg-success">@item.RoomStatus</span>
                                    }
                                    else if (@item.RoomStatus == RoomStatus.Booked)
                                    {
                                        <span class="badge text-bg-secondary">@item.RoomStatus</span>
                                    }
                                    else
                                    {
                                        <span class="badge text-bg-warning">@item.RoomStatus</span>
                                    }
                                }
                            </div>
                        </div>
                        <div class="list-container-action">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary m-1" style="width: 100%;">Edit</a>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-primary m-1" style="width: 100%">Remove</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>