hotel-management-mvc/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hotel_management_mvc.Models;
using Newtonsoft.Json;
using static System.TimeZoneInfo;

namespace hotel_management_mvc.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly HotelManagementContext _context;

        public TransactionsController(HotelManagementContext context)
        {
            _context = context;
        }

        // GET: Transactions
        public async Task<IActionResult> Index(string searchString)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            var transaction = await _context.Transactions.OrderByDescending(x => x.Id).ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                transaction = transaction.Where(x => x.CustomerName.Trim().ToLower().Contains(searchString.Trim().ToLower()) || x.BookingId.ToString().Trim().ToLower().Contains(searchString.Trim().ToLower()) || x.IsPaid.ToString().Trim().ToLower().Contains(searchString.Trim().ToLower())).ToList();
            }
            return transaction != null ?
                          View(transaction) :
                          Problem("Entity set 'HotelManagementContext.transaction'  is null.");
        }

        public IActionResult GetIncome(DateTime? startDate, DateTime? endTime)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            var transaction = _context.Transactions.Where(x => x.IsPaid == BookingStatus.Paid).Sum(x => x.Total);
            if (startDate != null && endTime != null)
            {
                transaction = _context.Transactions.Where(x => x.IsPaid == BookingStatus.Paid && x.TransactionTime >= startDate && x.TransactionTime <= endTime).Sum(x => x.Total);
            }
            return Json(transaction);
        }

        // GET: Transactions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Booking)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }
            var availableRooms = _context.RoomTransactions.Include(x => x.Room).Where(x => x.TransactionId == id).ToList();
            TempData["AvailableRooms"] = availableRooms;

            return View(transaction);
        }

        // GET: Transactions/Create
        public IActionResult Create()
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            ViewData["BookingId"] = new SelectList(_context.Bookings, "Id", "Id");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Total,TransactionTime,IsPaid,Note,CustomerName,BookingId")] Transaction transaction)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (ModelState.IsValid)
            {
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookingId"] = new SelectList(_context.Bookings, "Id", "Id", transaction.BookingId);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            var availableRooms = _context.RoomTransactions.Include(x => x.Room).Where(x => x.TransactionId == id).ToList();
            TempData["AvailableRooms"] = availableRooms;
            ViewData["BookingId"] = new SelectList(_context.Bookings, "Id", "Id", transaction.BookingId);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Total,TransactionTime,IsPaid,Note,CustomerName,BookingId")] Transaction transaction)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BookingId"] = new SelectList(_context.Bookings, "Id", "Id", transaction.BookingId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Booking)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (role.Role != "Admin")
            {
                return View("Error");
            }
            if (_context.Transactions == null)
            {
                return Problem("Entity set 'HotelManagementContext.Transactions'  is null.");
            }
            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction != null)
            {
                _context.Transactions.Remove(transaction);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
            return (_context.Transactions?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

hotel-management-mvc/Views/Transactions/Details.cshtml
@model hotel_management_mvc.Models.Transaction

@{
    ViewData["Title"] = "Details";
}
@{
    var rooms = (List<RoomTransaction>)TempData["AvailableRooms"] != null ? (List<RoomTransaction>)TempData["AvailableRooms"] : new List<RoomTransaction>();
}

<div>
    <div class="edit-header">
        <h4>Transaction Details</h4>
        <div>
            <a asp-action="Index" class="btn btn-primary m-1">Back to Transaction List</a>
        </div>
    </div>
    <hr />

    <div class="pt-3 d-flex gap-5 justify-content-start">
        <div>
            <table class="table">
                <tbody>
                    @foreach (var room in rooms)
                    {
                        <tr>
                            <th>Room Code</th>
                            <td>@room.Room.Code</td>
                        </tr>
                    }
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Total)</th>
                        <td>@Html.DisplayFor(model => model.Total)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.TransactionTime)</th>
                        <td>@Html.DisplayFor(model => model.TransactionTime)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.IsPaid)</th>
                        <td>@Html.DisplayFor(model => model.IsPaid)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Note)</th>
                        <td>@Html.DisplayFor(model => model.Note)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.CustomerName)</th>
                        <td>@Html.DisplayFor(model => model.CustomerName)</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div>
            <table class="table">
                <tbody>
                    <tr>
                        <th>Booking ID</th>
                        <td>@Html.DisplayFor(model => model.Booking.Id)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.Checkin)</th>
                        <td>@Html.DisplayFor(model => model.Booking.Checkin)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.Checkout)</th>
                        <td>@Html.DisplayFor(model => model.Booking.Checkout)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.BookingStatus)</th>
                        <td>@Html.DisplayFor(model => model.Booking.BookingStatus)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.Note)</th>
                        <td>@Html.DisplayFor(model => model.Booking.Note)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.CustomerPhone)</th>
                        <td>@Html.DisplayFor(model => model.Booking.CustomerPhone)</td>
                    </tr>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.Booking.PayMethod)</th>
                        <td>@Html.DisplayFor(model => model.Booking.PayMethod)</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
<div class="mt-3">
        <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary m-1">Edit</a>
</div>

hotel-management-mvc/Views/Transactions/Edit.cshtml
@model hotel_management_mvc.Models.Transaction

@{
    ViewData["Title"] = "Edit";
}
@{
    var rooms = (List<RoomTransaction>)TempData["AvailableRooms"] != null ? (List<RoomTransaction>)TempData["AvailableRooms"] : new List<RoomTransaction>();
}

<div class="edit-header">
    <h4>Transaction</h4>
    <div>
        <a asp-action="Index" class="btn btn-primary m-1">Back to Transaction List</a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @{
                foreach (var room in rooms)
                {
                    <div class="d-flex justify-content-start align-items-center">
                        <strong>Room Code: @room.Room.Code</strong>
                    </div>
                }
            }
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionTime" class="control-label"></label>
                <input asp-for="TransactionTime" class="form-control" readonly/>
                <span asp-validation-for="TransactionTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsPaid" class="control-label"></label>
                <select asp-for="IsPaid" class="form-control">
                    <option value="1">Paid</option>
                    <option value="2">Unpaid</option>
                </select>
                <span asp-validation-for="IsPaid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" readonly/>
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookingId" class="control-label"></label>
                <input asp-for="BookingId" class="form-control" readonly />
                <span asp-validation-for="BookingId" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

hotel-management-mvc/Views/Transactions/Index.cshtml
@model IEnumerable<hotel_management_mvc.Models.Transaction>

@{
    ViewData["Title"] = "Transaction";
}

<div class="page-header">
    <h1><strong>Transaction List</strong></h1>
</div>
<div class="page-title">
    <div class="page-title-search">
        <form asp-controller="Transactions" asp-action="Index">
            <p>
                Search: <input type="text" name="SearchString" />
                <input type="submit" value="Search" />
            </p>
        </form>
        <p>
            Start Date: <input type="datetime-local" id="startDate" />
            End Time: <input type="datetime-local" id="endTime" />
            <input type="button" id="getIncomeBtn" value="Get Income" />
        </p>
        <strong>Total: <span id="income"></span> - vnd</strong>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Total
            </th>
            <th>
                Transaction Time
            </th>
            <th>
                Transaction Status
            </th>
            <th>
                Note
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Booking Id
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransactionTime)
                </td>
                <td>
                    @{
                        if (@item.IsPaid == BookingStatus.Paid)
                        {
                            <span class="badge text-bg-success">@item.IsPaid</span>
                        }
                        else
                        {
                            <span class="badge text-bg-warning">@item.IsPaid</span>
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookingId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $('#getIncomeBtn').on('click', function () {
        var startDate = $('#startDate').val();
        var endTime = $('#endTime').val();

        $.ajax({
            url: '@Url.Action("GetIncome", "Transactions")',
            type: "GET",
            data: {
                startDate: startDate,
                endTime: endTime
            },
            success: function (response) {
                $('#income').text(response);
            },
            error: function (response) {
                // Handle error here
            }
        });
    });
</script>