hotel-management-mvc/Models/Booking.cs
using System;
using System.Collections.Generic;

namespace hotel_management_mvc.Models;

public partial class Booking
{
    public int Id { get; set; }

    public DateTime Checkin { get; set; }

    public DateTime Checkout { get; set; }

    public BookingStatus BookingStatus { get; set; }

    public string? Note { get; set; }

    public string CustomerName { get; set; } = null!;

    public string CustomerPhone { get; set; } = null!;

    public PayMethod PayMethod { get; set; }

    public virtual ICollection<RoomBooking> RoomBookings { get; set; } = new List<RoomBooking>();

    public virtual Transaction? Transaction { get; set; }
}

hotel-management-mvc/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using hotel_management_mvc.Models;
using Newtonsoft.Json;

namespace hotel_management_mvc.Controllers
{
    public class BookingsController : Controller
    {
        private readonly HotelManagementContext _context;
        public BookingsController(HotelManagementContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index(string searchString)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            var bookings = await _context.Bookings.OrderByDescending(x => x.Id).ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {
                bookings = bookings.Where(x => x.CustomerName.Trim().ToLower().Contains(searchString.Trim().ToLower()) || x.Checkin.ToString().Trim().ToLower().Contains(searchString.Trim().ToLower()) || x.Checkout.ToString().Trim().ToLower().Contains(searchString.Trim().ToLower())).ToList();
            }
            return bookings != null ?
                          View(bookings) :
                          Problem("Entity set 'HotelManagementContext.Bookings'  is null.");
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }
            var availableRooms = _context.RoomBookings.Include(x => x.Room).Where(x => x.BookingId == id).ToList();
            TempData["AvailableRooms"] = availableRooms;
            return View(booking);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            var availableRooms = _context.Rooms.Where(x => x.RoomStatus == RoomStatus.Empty).ToList();
            TempData["AvailableRooms"] = availableRooms;

            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Checkin,Checkout,BookingStatus,Note,CustomerName,CustomerPhone,PayMethod")] Booking booking, int selectedRoom)
        {
            if (ModelState.IsValid && selectedRoom > 0)
            {
                var room = await _context.Rooms.FirstOrDefaultAsync(x => x.Id == selectedRoom);
                var roomBooking = new RoomBooking { RoomId = selectedRoom };
                var transaction = new Transaction
                {
                    Total = room.Price,
                    TransactionTime = DateTime.Now,
                    IsPaid = booking.BookingStatus,
                    CustomerName = booking.CustomerName
                };
                room.RoomStatus = RoomStatus.Booked;
                booking.RoomBookings.Add(roomBooking);
                booking.Transaction = transaction;
                var roomTransaction = new RoomTransaction { RoomId = selectedRoom };
                transaction.RoomTransactions.Add(roomTransaction);
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Details), new { id = booking.Id });
            }
            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            var availableRooms = _context.RoomBookings.Include(x => x.Room).Where(x => x.BookingId == id).ToList();
            TempData["AvailableRooms"] = availableRooms;
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Checkin,Checkout,BookingStatus,Note,CustomerName,CustomerPhone,PayMethod")] Booking booking)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var value = HttpContext.Session.GetString("role");
            if (value == null)
            {
                return View("Error");
            }
            var role = JsonConvert.DeserializeObject<AuthenModel>(value);
            if (_context.Bookings == null)
            {
                return Problem("Entity set 'HotelManagementContext.Bookings'  is null.");
            }
            var booking = await _context.Bookings.FindAsync(id);
            if (booking != null)
            {
                _context.Bookings.Remove(booking);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return (_context.Bookings?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public IActionResult GetRoomDetails(int selectedRoom)
        {
            if (selectedRoom > 0)
            {
                var room = _context.Rooms.FirstOrDefault(x => x.Id == selectedRoom);
                return Json(room);
            }
            var emptyRoom = new Room();
            return Json(emptyRoom);
        }
    }
}

hotel-management-mvc/Views/Bookings/Create.cshtml
@model hotel_management_mvc.Models.Booking

@{
    ViewData["Title"] = "Create";
}
@{
    var rooms = (List<Room>)TempData["AvailableRooms"] != null ? (List<Room>)TempData["AvailableRooms"] : new List<Room>();
    var room = (Room)TempData["SelectedRoom"];
}

<div class="edit-header">
    <h4>Create Booking</h4>
    <div>
        <a asp-action="Index" class="btn btn-primary m-1">Back to Bookings List</a>
    </div>
</div>
<hr />
<div class="d-flex gap-5">
    <div class="row w-100">
        <div class="col-md-4 w-100">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">Selected Room</label>
                    <select class="form-control" name="selectedRoom" id="selectedRoomDropdown">
                        <option value="0">Select room ...</option>
                        @{
                            foreach (var item in rooms)
                            {
                                <option value="@item.Id">Code: @item.Code</option>
                            }
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="Checkin" class="control-label"></label>
                    <input asp-for="Checkin" class="form-control" />
                    <span asp-validation-for="Checkin" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Checkout" class="control-label"></label>
                    <input asp-for="Checkout" class="form-control" />
                    <span asp-validation-for="Checkout" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BookingStatus" class="control-label"></label>
                    <select asp-for="BookingStatus" class="form-control">
                        <option value="1">Paid</option>
                        <option value="2">Unpaid</option>
                    </select>
                    <span asp-validation-for="PayMethod" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Note" class="control-label"></label>
                    <input asp-for="Note" class="form-control" />
                    <span asp-validation-for="Note" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerName" class="control-label"></label>
                    <input asp-for="CustomerName" class="form-control" />
                    <span asp-validation-for="CustomerName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerPhone" class="control-label"></label>
                    <input asp-for="CustomerPhone" class="form-control" />
                    <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PayMethod" class="control-label"></label>
                    <select asp-for="PayMethod" class="form-control">
                        <option value="1">Cash</option>
                        <option value="2">Card</option>
                    </select>
                    <span asp-validation-for="PayMethod" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
    <div class="w-100">
        <table class="table">
            <tbody>
                <tr>
                    <th>Room ID</th>
                    <td id="roomId"></td>
                </tr>
                <tr>
                    <th>Room Code</th>
                    <td id="roomCode"></td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td id="roomPrice"></td>
                </tr>
                <tr>
                    <th>Services</th>
                    <td id="roomServices"></td>
                </tr>
                <tr>
                    <th>Room Status</th>
                    <td id="roomStatus"></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    var url = '@Url.Action("GetRoomDetails", "Bookings")';
    $('#selectedRoomDropdown').on('change', function () {
        var value = $('select#selectedRoomDropdown').val()
        if (value) {
            $.ajax({
                url: '@Url.Action("GetRoomDetails", "Bookings")',
                type: "GET",
                data: { selectedRoom: value },
                success: function (response) {
                    $('#roomId').text(response.id);
                    $('#roomCode').text(response.code);
                    $('#roomPrice').text(response.price);
                    $('#roomServices').text(response.services);
                    $('#roomStatus').text(response.roomStatus);
                },
                error: function (response) {
                }
            });
        }
    });
</script>

hotel-management-mvc/Views/Bookings/Delete.cshtml
@model hotel_management_mvc.Models.Booking

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Booking</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Checkin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Checkin)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Checkout)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Checkout)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookingStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookingStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayMethod)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayMethod)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

hotel-management-mvc/Views/Bookings/Details.cshtml
@model hotel_management_mvc.Models.Booking

@{
    ViewData["Title"] = "Details";
}
@{
    var rooms = (List<RoomBooking>)TempData["AvailableRooms"] != null ? (List<RoomBooking>)TempData["AvailableRooms"] : new List<RoomBooking>();
}

<div>
    <div class="edit-header">
        <h4>Booking Details</h4>
        <div>
            <a asp-action="Index" class="btn btn-primary m-1">Back to Bookings List</a>
        </div>
    </div>
    <hr />
    <div>
        <table class="table">
            <tbody>
                @{
                    foreach (var room in rooms)
                    {
                        <tr>
                            <th>Room Code</th>
                            <td>@room.Room.Code</td>
                        </tr>
                    }
                }   
                <tr>
                    <th>Booking ID</th>
                    <td>@Html.DisplayFor(model => model.Id)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Checkin)</th>
                    <td>@Html.DisplayFor(model => model.Checkin)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Checkout)</th>
                    <td>@Html.DisplayFor(model => model.Checkout)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.BookingStatus)</th>
                    <td>@Html.DisplayFor(model => model.BookingStatus)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Note)</th>
                    <td>@Html.DisplayFor(model => model.Note)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.CustomerPhone)</th>
                    <td>@Html.DisplayFor(model => model.CustomerPhone)</td>
                </tr>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.PayMethod)</th>
                    <td>@Html.DisplayFor(model => model.PayMethod)</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="mt-3">
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary m-1">Edit</a>
</div>

hotel-management-mvc/Views/Bookings/Edit.cshtml
@model hotel_management_mvc.Models.Booking

@{
    ViewData["Title"] = "Edit";
}
@{
    var rooms = (List<RoomBooking>)TempData["AvailableRooms"] != null ? (List<RoomBooking>)TempData["AvailableRooms"] : new List<RoomBooking>();
}

<div class="edit-header">
    <h4>Edit Booking</h4>
    <div>
        <a asp-action="Index" class="btn btn-primary m-1">Back to Bookings List</a>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label class="control-label"></label>
                @{
                    foreach (var item in rooms)
                    {
                        <input value="@item.Room.Code" class="form-control" readonly/>
                    }
                }
            </div>
            <div class="form-group">
                <label asp-for="Checkin" class="control-label"></label>
                <input asp-for="Checkin" class="form-control" />
                <span asp-validation-for="Checkin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Checkout" class="control-label"></label>
                <input asp-for="Checkout" class="form-control" />
                <span asp-validation-for="Checkout" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookingStatus" class="control-label"></label>
                <select asp-for="BookingStatus" class="form-control">
                    <option value="1">Paid</option>
                    <option value="2">Unpaid</option>
                </select>
                <span asp-validation-for="PayMethod" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control" />
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerPhone" class="control-label"></label>
                <input asp-for="CustomerPhone" class="form-control" />
                <span asp-validation-for="CustomerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayMethod" class="control-label"></label>
                <select asp-for="PayMethod" class="form-control">
                    <option value="1">Cash</option>
                    <option value="2">Card</option>
                </select>
                <span asp-validation-for="PayMethod" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

hotel-management-mvc/Views/Bookings/Index.cshtml
@model IEnumerable<hotel_management_mvc.Models.Booking>

@{
    ViewData["Title"] = "Booking - Hotel Management";
}

<div class="page-header">
    <h1><strong>Booking List</strong></h1>
</div>
<div class="page-title">
    <div class="page-title-search">
        <form asp-controller="Bookings" asp-action="Index">
            <p>
                Search: <input type="text" name="SearchString" />
                <input type="submit" value="Search" />
            </p>
        </form>
    </div>
    <p class="page-title-button">
        <a asp-action="Create" class="btn btn-primary m-1" style="width: 100%;">Add new Booking</a>
    </p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Checkin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Checkout)
            </th>
            <th>
                Booking Status
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Customer Phone
            </th>
            <th>
                Pay Method
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Checkin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Checkout)
            </td>
                <td>
                    @{
                        if (@item.BookingStatus == BookingStatus.Paid)
                        {
                            <span class="badge text-bg-success">@item.BookingStatus</span>
                        }
                        else
                        {
                            <span class ="badge text-bg-warning">@item.BookingStatus</span>
                        }
                    }
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayMethod)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>